######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 22 11:15:37 2017
######################################################################

TEMPLATE = app
TARGET = whiten
DEPENDPATH += .
INCLUDEPATH += /usr/include/opencv2
LIBS +=  -lopencv_core -lopencv_imgproc -lopencv_objdetect

# Input
HEADERS += canvas.h main.h
FORMS += mainwindow.ui
SOURCES += canvas.cpp main.cpp

